2025-06-05 17:11:03,587 INFO: 
======================================================================
2025-06-05 17:11:03,587 INFO: ▶  PROCESSO FILE: dati_2014.csv
2025-06-05 17:11:03,587 INFO: ======================================================================
2025-06-05 17:11:03,587 INFO: ▶  ho caricato e pulito i dati
2025-06-05 17:11:03,588 INFO: [load_pois] 22 POI letti da /Users/simo/Downloads/LLM-Mob-As-Mobility-Interpreter/data/verona/vc_site.csv
2025-06-05 17:11:04,194 INFO: [load_visits] 370377 timbrature da /Users/simo/Downloads/LLM-Mob-As-Mobility-Interpreter/data/verona/dataset_veronacard_2014_2020/dati_2014.csv
2025-06-05 17:11:04,245 INFO: [merge] visite valide dopo merge: 370377
2025-06-05 17:11:04,330 INFO: [filter] card multi-visita: 70236 / 71557
2025-06-05 17:11:04,471 INFO: ▶  ho fatto il clustering
2025-06-05 17:11:04,491 INFO: ✔  Salvato dati_2014_pred_20250605_171104.csv – Hit@5: nan%
2025-06-05 17:11:04,608 INFO: 
======================================================================
2025-06-05 17:11:04,608 INFO: ▶  PROCESSO FILE: dati_2015.csv
2025-06-05 17:11:04,608 INFO: ======================================================================
2025-06-05 17:11:04,608 INFO: ▶  ho caricato e pulito i dati
2025-06-05 17:11:04,608 INFO: [load_pois] 22 POI letti da /Users/simo/Downloads/LLM-Mob-As-Mobility-Interpreter/data/verona/vc_site.csv
2025-06-05 17:11:05,209 INFO: [load_visits] 369587 timbrature da /Users/simo/Downloads/LLM-Mob-As-Mobility-Interpreter/data/verona/dataset_veronacard_2014_2020/dati_2015.csv
2025-06-05 17:11:05,261 INFO: [merge] visite valide dopo merge: 369587
2025-06-05 17:11:05,347 INFO: [filter] card multi-visita: 71759 / 73424
2025-06-05 17:11:05,461 INFO: ▶  ho fatto il clustering
2025-06-05 17:11:05,464 INFO: ✔  Salvato dati_2015_pred_20250605_171105.csv – Hit@5: nan%
2025-06-05 17:11:05,592 INFO: 
======================================================================
2025-06-05 17:11:05,592 INFO: ▶  PROCESSO FILE: dati_2016.csv
2025-06-05 17:11:05,592 INFO: ======================================================================
2025-06-05 17:11:05,592 INFO: ▶  ho caricato e pulito i dati
2025-06-05 17:11:05,594 INFO: [load_pois] 22 POI letti da /Users/simo/Downloads/LLM-Mob-As-Mobility-Interpreter/data/verona/vc_site.csv
2025-06-05 17:11:06,229 INFO: [load_visits] 383516 timbrature da /Users/simo/Downloads/LLM-Mob-As-Mobility-Interpreter/data/verona/dataset_veronacard_2014_2020/dati_2016.csv
2025-06-05 17:11:06,279 INFO: [merge] visite valide dopo merge: 383516
2025-06-05 17:11:06,368 INFO: [filter] card multi-visita: 76451 / 78152
2025-06-05 17:11:06,490 INFO: ▶  ho fatto il clustering
2025-06-05 17:11:06,493 INFO: ✔  Salvato dati_2016_pred_20250605_171106.csv – Hit@5: nan%
2025-06-05 17:11:06,634 INFO: 
======================================================================
2025-06-05 17:11:06,634 INFO: ▶  PROCESSO FILE: dati_2017.csv
2025-06-05 17:11:06,634 INFO: ======================================================================
2025-06-05 17:11:06,635 INFO: ▶  ho caricato e pulito i dati
2025-06-05 17:11:06,635 INFO: [load_pois] 22 POI letti da /Users/simo/Downloads/LLM-Mob-As-Mobility-Interpreter/data/verona/vc_site.csv
2025-06-05 17:11:07,353 INFO: [load_visits] 441594 timbrature da /Users/simo/Downloads/LLM-Mob-As-Mobility-Interpreter/data/verona/dataset_veronacard_2014_2020/dati_2017.csv
2025-06-05 17:11:07,430 INFO: [merge] visite valide dopo merge: 441594
2025-06-05 17:11:07,533 INFO: [filter] card multi-visita: 89352 / 91554
2025-06-05 17:11:07,701 INFO: ▶  ho fatto il clustering
2025-06-05 17:11:07,706 INFO: ✔  Salvato dati_2017_pred_20250605_171107.csv – Hit@5: nan%
2025-06-05 17:11:07,838 INFO: 
======================================================================
2025-06-05 17:11:07,838 INFO: ▶  PROCESSO FILE: dati_2018.csv
2025-06-05 17:11:07,838 INFO: ======================================================================
2025-06-05 17:11:07,838 INFO: ▶  ho caricato e pulito i dati
2025-06-05 17:11:07,839 INFO: [load_pois] 22 POI letti da /Users/simo/Downloads/LLM-Mob-As-Mobility-Interpreter/data/verona/vc_site.csv
2025-06-05 17:11:08,533 INFO: [load_visits] 427213 timbrature da /Users/simo/Downloads/LLM-Mob-As-Mobility-Interpreter/data/verona/dataset_veronacard_2014_2020/dati_2018.csv
2025-06-05 17:11:08,587 INFO: [merge] visite valide dopo merge: 427213
2025-06-05 17:11:08,687 INFO: [filter] card multi-visita: 86221 / 88627
2025-06-05 17:11:08,852 INFO: ▶  ho fatto il clustering
2025-06-05 17:11:08,856 INFO: ✔  Salvato dati_2018_pred_20250605_171108.csv – Hit@5: nan%
2025-06-05 17:11:08,863 INFO: 
======================================================================
2025-06-05 17:11:08,863 INFO: ▶  PROCESSO FILE: dati_2019.csv
2025-06-05 17:11:08,863 INFO: ======================================================================
2025-06-05 17:11:08,863 INFO: ▶  ho caricato e pulito i dati
2025-06-05 17:11:08,864 INFO: [load_pois] 22 POI letti da /Users/simo/Downloads/LLM-Mob-As-Mobility-Interpreter/data/verona/vc_site.csv
2025-06-05 17:11:09,586 INFO: [load_visits] 397561 timbrature da /Users/simo/Downloads/LLM-Mob-As-Mobility-Interpreter/data/verona/dataset_veronacard_2014_2020/dati_2019.csv
2025-06-05 17:11:09,638 INFO: [merge] visite valide dopo merge: 397561
2025-06-05 17:11:09,734 INFO: [filter] card multi-visita: 77583 / 79825
2025-06-05 17:11:11,794 INFO: ▶  ho fatto il clustering
2025-06-05 17:11:11,874 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108fcd710>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:11,900 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113a36690>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:11,926 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x111368810>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:11,951 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113a36a90>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:11,976 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113a34850>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,001 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f591ad0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,025 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113a362d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,050 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11136bc90>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,074 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f591d10>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,098 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f590750>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,123 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f590150>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,147 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b2a490>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,171 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113a36190>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,195 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113a36ad0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,221 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113a35190>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,245 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b29f50>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,270 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f591fd0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,295 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x116eee050>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,321 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f5928d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,347 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113a37e90>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,376 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x111369c10>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,402 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x116eef6d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,427 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x116eed510>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,452 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x111368d50>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,476 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b2a4d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,501 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f592810>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,525 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f5921d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,550 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b29590>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,574 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11136a310>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,599 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x116eee1d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,624 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x116eee1d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,647 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113a36250>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,672 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f591b90>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,696 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10e0a1b90>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,724 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b28510>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,748 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113a34b50>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,772 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x116eee390>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,797 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11139acd0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,822 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x116eed990>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,847 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113a35490>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,871 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b2b9d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,895 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x111399f90>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,920 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10f593e10>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,944 ERROR: ❌  Connessione Ollama fallita: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/tags (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ce8df10>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-06-05 17:11:12,946 INFO: Interruzione manuale...
